"""Initial migration testing absolute path

Revision ID: 919b87616b2b
Revises: 
Create Date: 2025-04-10 15:36:19.518747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919b87616b2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toll_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_lat', sa.Float(), nullable=True),
    sa.Column('entry_lon', sa.Float(), nullable=True),
    sa.Column('entry_address', sa.String(length=255), nullable=True),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=True),
    sa.Column('exit_lat', sa.Float(), nullable=True),
    sa.Column('exit_lon', sa.Float(), nullable=True),
    sa.Column('exit_address', sa.String(length=255), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('payment_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_entry_only', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toll_record')
    op.drop_table('query')
    op.drop_table('user')
    # ### end Alembic commands ###
